services:
  db:
    image: postgres:16
    container_name: taller-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taller_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taller_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: taller-app
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taller_db
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
